import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		double sumall = 0;
		int count2Children = 0;
		int count3Children = 0;
		int count4AndMore = 0;
		double avg;

		for(int i = 0; i < T; i++)
		{
			boolean girl = false;
			boolean boy = false;
			double sum = 0;
			while (!(boy && girl)){
			double x = generator.nextDouble();
			if(x < 0.5){
				girl = true;
			} else{
				boy = true;
			  }
			sum = sum + 1;
			}
			if(sum == 2){
				count2Children++;
			} else if(sum ==3) {
              	count3Children++;
			} else if(sum >= 4){
				count4AndMore++;
			}
			sumall = sumall + sum;
			sum = 0;

		}
		String common = "2";
		if(count3Children > count2Children){
			common = "3";
			if(count4AndMore > count3Children){
				common = "4 and more";
			}
		} else if(count4AndMore > count2Children){
			common = "4 and more";
		} 
		avg = sumall/T;
		System.out.println("Average: " + avg + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + count2Children);
		System.out.println("Number of families with 3 children: " + count3Children);
		System.out.println("Number of families with 4 or more children: " + count4AndMore);
		System.out.println("The most common number of children is " + common +".");

		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}
